logging:
    path: usr/local/logs/creative/prod/

spring:
    redis:
        host: 10.70.1.10
        port: 6379
        password:
        jedis:
            pool:
                max-active: 8   #最大连接数
                max-idle: 8     #最大空闲
                min-idle: 5     #最小空闲
                timeout: 1000  #连接超时时间
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.70.6.15:3306/creative_post?autoCommit=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
        username: creative_post
        password: 0m9n3b5x8hPW
        hikari:
            connection-test-query: SELECT 1
            maximum-pool-size: 20
            minimum-idle: 3
            max-lifetime: 60000
            validation-timeout: 60000
    cloud:
        consul:
            config:
                enabled: false
            discovery:
                prefer-ip-address: true
                ip-address: yx-creative-post
                port: 9088
            host: consul-server-bootstrap
            port: 8500
        sentinel:
            transport:
                dashboard: 10.70.1.10:38080
            thymeleaf:
                cache: false

jetcache:
    statIntervalMinutes: 15
    areaInCacheName: false
    local:
        default:
            type: caffeine
            keyConvertor: fastjson
            expireAfterWriteInMillis: 100000
    remote:
        default:
            type: redis
            keyConvertor: fastjson
            valueEncoder: kryo
            valueDecoder: kryo
            poolConfig:
                minIdle: 5
                maxIdle: 60
                maxTotal: 500
            host: 10.70.1.10
            port: 6379

rocketmq:
    producer:
        isOnOff: on
        groupName: ${spring.application.name}-${roketmq.groups.producer.name}   #发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
        namesrvAddr: 192.168.20.161:9876;192.168.20.171:9876
        maxMessageSize: 4096
        sendMsgTimeout: 3000
        retryTimesWhenSendFailed: 3
    consumer:
        isOnOff: on
        groupName: ${spring.application.name}-${roketmq.groups.consumer.name}
        namesrvAddr: 192.168.20.161:9876;192.168.20.171:9876
        topics: creative-post~*;
        consumeThreadMin: 20
        consumeThreadMax: 64
        consumeMessageBatchMaxSize: 1

firefly:
    gateway:
        rate-limiting:
            enabled: false
            limit: 100000
            duration-in-seconds: 3600
    http:
        version: V_1_1 # To use HTTP/2 you will need SSL support (see above the "server.ssl" configuration)
    cors:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"
        exposed-headers: "Authorization,Pagination"
        allow-credentials: true
        max-age: 1800
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx:
            enabled: true
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            report-frequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: true
            host: 192.168.20.36
            port: 9250
            queue-size: 512
feign:
    hystrix:
        enabled: true
    client:
        config:
            default:
                connectTimeout: 50000
                readTimeout: 50000

# See https://github.com/Netflix/Hystrix/wiki/Configuration
hystrix:
    command:
        default:
            execution:
                isolation:
                    strategy: SEMAPHORE
                    thread:
                        timeoutInMilliseconds: 100000
    shareSecurityContext: true

creative:
    remote:
        url:
            melly: https://meilly-api.meilly.cn

melly:
    expires: 60
    access-key: "ecb1bf421d7141de94bf10c28462fc74"
    secretKey: "3a037f25b0fa485dad183f953d65115c"
    note-list: http://meilly-api.my.yingyingwork.com/note-api/open-api/note
    note-detail: http://meilly-api.my.yingyingwork.com/note-api/open-api/notes/{noteNo}

xxl:
    job:
        admin:
            addresses: http://job.yingyinglicai.com
        executor:
            appname: creative-post-timing-send
            ip:
            port: 9997
            logpath: /tmp/logs
            logretentiondays: -1
        accessToken:

