server:
    port: 9088
logging:
    config: classpath:logback-spring.xml
    level:
        com.yingxin.creative: INFO
        ROOT: INFO
        com.yingnagroup.yinghuo.firefly: INFO

spring:
    aop:
        auto: true
        proxy-target-class: true

    profiles:
        active: development
        include: swagger

    application:
        name: creative-post
    jackson:
        serialization.indent_output: true
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    cloud:
        consul:
            discovery:
                health-check-path: /management/post/health
                instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
            config:
                watch:
                    enabled: false
    mvc:
        favicon:
            enabled: false
    main:
        allow-bean-definition-overriding: true
    autoconfigure:
        exclude: com.yingnagroup.yinghuo.firefly.config.properites.DubboProperties


mybatis:
    mapper-locations: classpath*:xml/**/*Mapper.xml

management:
    endpoints:
        web:
            base-path: /management/post
            exposure:
                include: ["configprops", "env", "health", "info", "threaddump", "logfile" ]
    endpoint:
        health:
            show-details: when_authorized
    info:
        git:
            mode: full
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true
    metrics:
        enabled: false # http://micrometer.io/ is disabled by default, as we use http://metrics.dropwizard.io/ instead

firefly:
    swagger:
        default-include-pattern: /creative/.*
        title: creative-psot API
        description: creative-psotAPI文档
        version: 1.0.0
        terms-of-service-url:
        contact-name:
        contact-url:
        contact-email:
        license:
        license-url:
    async:
        core-pool-size: 10
        max-pool-size: 128
        queue-capacity: 10000

creative:
    service:
        out: true

