logging:
    path: usr/local/logs/creative/testing/

spring:
    redis:
        host: 10.100.2.36
        port: 6379
        password: yinghuo
        database: 1
        jedis:
            pool:
                max-active: 8   #最大连接数
                max-idle: 8     #最大空闲
                min-idle: 5     #最小空闲
                timeout: 1000  #连接超时时间
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.100.2.12:3306/forum-test?autoCommit=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
        username: root
        password: Wo4heike
        hikari:
            connection-test-query: SELECT 1
            maximum-pool-size: 20
            minimum-idle: 3
            max-lifetime: 60000
            validation-timeout: 60000
    cloud:
        consul:
            config:
                enabled: false
            discovery:
                prefer-ip-address: true
#                ip-address: 10.100.2.36
            host: 10.100.2.36
            port: 8500
        sentinel:
            transport:
                dashboard: 10.100.2.36:38080
            thymeleaf:
                cache: false


jetcache:
    statIntervalMinutes: 15
    areaInCacheName: false
    local:
        default:
            type: linkedhashmap
            keyConvertor: fastjson
            expireAfterWriteInMillis: 100000
    remote:
        default:
            type: redis
            keyConvertor: fastjson
            valueEncoder: kryo
            valueDecoder: kryo
            poolConfig:
                minIdle: 5
                maxIdle: 20
                maxTotal: 50
            host: 10.100.2.36
            port: 6379
            password: yinghuo

rocketmq:
    producer:
        isOnOff: on
        groupName: ${spring.application.name}-${roketmq.groups.producer.name}   #发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
        namesrvAddr: 10.100.20.179:9876
        maxMessageSize: 4096
        sendMsgTimeout: 3000
        retryTimesWhenSendFailed: 3
    consumer:
        isOnOff: on
        groupName: ${spring.application.name}-${roketmq.groups.consumer.name}
        namesrvAddr: 10.100.20.179:9876
        topics: creative-post~*;
        consumeThreadMin: 20
        consumeThreadMax: 64
        consumeMessageBatchMaxSize: 1

firefly:
    http:
        version: V_1_1 # To use HTTP/2 you will need SSL support (see above the "server.ssl" configuration)
    cors:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"
        exposed-headers: "Authorization,Pagination"
        allow-credentials: true
        max-age: 1800
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx:
            enabled: true
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            report-frequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: true
            host: 10.100.2.12
            port: 5000
            queue-size: 512

feign:
    hystrix:
        enabled: true
    client:
        config:
            default:
                connectTimeout: 5000
                readTimeout: 5000

# See https://github.com/Netflix/Hystrix/wiki/Configuration
hystrix:
    command:
        default:
            execution:
                isolation:
                    strategy: SEMAPHORE
                    thread:
                        timeoutInMilliseconds: 10000
    shareSecurityContext: true

creative:
    remote:
        url:
            thirdPartyUrl: http://www.baidu.com
