#  spring:
#     datasource:
#         url: jdbc:mysql://10.100.2.12:3306/creative-post-dev?autoCommit=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
#         username: root
#         password: Wo4heike
